In [1]:
import pandas as pd

In [7]:
def preprocessing(file_name,save):
    data_df = pd.read_json(file_name,lines=True)
    data_pp1 = data_df.drop(['_id','마일리지정보','세부정보'], axis=1)
    yonsei = pd.DataFrame()
    for i in range(0, len(data_pp1.index)):
        df1 = pd.DataFrame(data_pp1.iloc[i,:],).transpose()
        df2 = pd.DataFrame(data_df['마일리지정보'][i].items()).set_index(0).transpose()
        df1 = df1.reset_index()
        df2 = df2.reset_index()
        df3 = pd.concat([df1, df2], axis=1)
        yonsei = yonsei.append(df3)
    yonsei['중간값'] = 0
    yonsei['분산'] = 0
    yonsei['평균학년'] = 0
    yonsei['재수강비율'] = 0
    for i in range(0,len(data_df['세부정보'])):
        df1 = pd.DataFrame()
        print(i/len(data_df['세부정보']), "%", '작업중...')
        for j in range(0, len(data_df['세부정보'][i])):
            df2 = pd.DataFrame(data_df['세부정보'][i][j].items()).set_index(0).transpose()
            df1 = df1.append(df2)
            df1.set_index('순위', inplace=True)
            df1['마일리지'] = pd.to_numeric(df1['마일리지'])
            df1['학년'] = pd.to_numeric(df1['학년'])
            for k in range(0,len(df1)):
                if df1.iloc[k,4] == 'Y':
                    df1.iloc[k,4] = 0
                else:
                    df1.iloc[k,4] = 1
            yonsei.iloc[i,-4] = df1.loc[:,'마일리지'].median()
            yonsei.iloc[i,-3] = df1.loc[:,'마일리지'].var()
            yonsei.iloc[i,-2] = df1.loc[:,'학년'].mean()
            yonsei.iloc[i,-1] = df1.loc[:,'초수강여부'].mean()
    yonsei.to_excel(save)
    return yonsei

In [8]:
preprocessing('./DataGongdae.json','tt.xlsx')

0.0 % 작업중...
0.002688172043010753 % 작업중...
0.005376344086021506 % 작업중...
0.008064516129032258 % 작업중...
0.010752688172043012 % 작업중...
0.013440860215053764 % 작업중...
0.016129032258064516 % 작업중...
0.01881720430107527 % 작업중...
0.021505376344086023 % 작업중...
0.024193548387096774 % 작업중...
0.026881720430107527 % 작업중...
0.02956989247311828 % 작업중...
0.03225806451612903 % 작업중...
0.03494623655913978 % 작업중...
0.03763440860215054 % 작업중...
0.04032258064516129 % 작업중...
0.043010752688172046 % 작업중...
0.0456989247311828 % 작업중...
0.04838709677419355 % 작업중...
0.051075268817204304 % 작업중...
0.053763440860215055 % 작업중...
0.056451612903225805 % 작업중...
0.05913978494623656 % 작업중...
0.06182795698924731 % 작업중...
0.06451612903225806 % 작업중...
0.06720430107526881 % 작업중...
0.06989247311827956 % 작업중...
0.07258064516129033 % 작업중...
0.07526881720430108 % 작업중...
0.07795698924731183 % 작업중...
0.08064516129032258 % 작업중...
0.08333333333333333 % 작업중...
0.08602150537634409 % 작업중...
0.08870967741935484 % 작업중...
0.0913978494623656 % 작업중...
0.09408602150537634 % 작업중...
0.0967741935483871 % 작업중...
0.09946236559139784 % 작업중...
0.10215053763440861 % 작업중...
0.10483870967741936 % 작업중...
0.10752688172043011 % 작업중...
0.11021505376344086 % 작업중...
0.11290322580645161 % 작업중...
0.11559139784946236 % 작업중...
0.11827956989247312 % 작업중...
0.12096774193548387 % 작업중...
0.12365591397849462 % 작업중...
0.12634408602150538 % 작업중...
0.12903225806451613 % 작업중...
0.13172043010752688 % 작업중...
0.13440860215053763 % 작업중...
0.13709677419354838 % 작업중...
0.13978494623655913 % 작업중...
0.1424731182795699 % 작업중...
0.14516129032258066 % 작업중...
0.1478494623655914 % 작업중...
0.15053763440860216 % 작업중...
0.1532258064516129 % 작업중...
0.15591397849462366 % 작업중...
0.1586021505376344 % 작업중...
0.16129032258064516 % 작업중...
0.1639784946236559 % 작업중...
0.16666666666666666 % 작업중...
0.1693548387096774 % 작업중...
0.17204301075268819 % 작업중...
0.17473118279569894 % 작업중...
0.1774193548387097 % 작업중...
0.18010752688172044 % 작업중...
0.1827956989247312 % 작업중...
0.18548387096774194 % 작업중...
0.1881720430107527 % 작업중...
0.19086021505376344 % 작업중...
0.1935483870967742 % 작업중...
0.19623655913978494 % 작업중...
0.1989247311827957 % 작업중...
0.20161290322580644 % 작업중...
0.20430107526881722 % 작업중...
0.20698924731182797 % 작업중...
0.20967741935483872 % 작업중...
0.21236559139784947 % 작업중...
0.21505376344086022 % 작업중...
0.21774193548387097 % 작업중...
0.22043010752688172 % 작업중...
0.22311827956989247 % 작업중...
0.22580645161290322 % 작업중...
0.22849462365591397 % 작업중...
0.23118279569892472 % 작업중...
0.23387096774193547 % 작업중...
0.23655913978494625 % 작업중...
0.239247311827957 % 작업중...
0.24193548387096775 % 작업중...
0.2446236559139785 % 작업중...
0.24731182795698925 % 작업중...
0.25 % 작업중...
0.25268817204301075 % 작업중...
0.2553763440860215 % 작업중...
0.25806451612903225 % 작업중...
0.260752688172043 % 작업중...
0.26344086021505375 % 작업중...
0.2661290322580645 % 작업중...
0.26881720430107525 % 작업중...
0.271505376344086 % 작업중...
0.27419354838709675 % 작업중...
0.2768817204301075 % 작업중...
0.27956989247311825 % 작업중...
0.28225806451612906 % 작업중...
0.2849462365591398 % 작업중...
0.28763440860215056 % 작업중...
0.2903225806451613 % 작업중...
0.29301075268817206 % 작업중...
0.2956989247311828 % 작업중...
0.29838709677419356 % 작업중...
0.3010752688172043 % 작업중...
0.30376344086021506 % 작업중...
0.3064516129032258 % 작업중...
0.30913978494623656 % 작업중...
0.3118279569892473 % 작업중...
0.31451612903225806 % 작업중...
0.3172043010752688 % 작업중...
0.31989247311827956 % 작업중...
0.3225806451612903 % 작업중...
0.32526881720430106 % 작업중...
0.3279569892473118 % 작업중...
0.33064516129032256 % 작업중...
0.3333333333333333 % 작업중...
0.33602150537634407 % 작업중...
0.3387096774193548 % 작업중...
0.34139784946236557 % 작업중...
0.34408602150537637 % 작업중...
0.3467741935483871 % 작업중...
0.34946236559139787 % 작업중...
0.3521505376344086 % 작업중...
0.3548387096774194 % 작업중...
0.3575268817204301 % 작업중...
0.3602150537634409 % 작업중...
0.3629032258064516 % 작업중...
0.3655913978494624 % 작업중...
0.3682795698924731 % 작업중...
0.3709677419354839 % 작업중...
0.3736559139784946 % 작업중...
0.3763440860215054 % 작업중...
0.3790322580645161 % 작업중...
0.3817204301075269 % 작업중...
0.3844086021505376 % 작업중...
0.3870967741935484 % 작업중...
0.3897849462365591 % 작업중...
0.3924731182795699 % 작업중...
0.3951612903225806 % 작업중...
0.3978494623655914 % 작업중...
0.40053763440860213 % 작업중...
0.4032258064516129 % 작업중...
0.40591397849462363 % 작업중...
0.40860215053763443 % 작업중...
0.4112903225806452 % 작업중...
0.41397849462365593 % 작업중...
0.4166666666666667 % 작업중...
0.41935483870967744 % 작업중...
0.4220430107526882 % 작업중...
0.42473118279569894 % 작업중...
0.4274193548387097 % 작업중...
0.43010752688172044 % 작업중...
0.4327956989247312 % 작업중...
0.43548387096774194 % 작업중...
0.4381720430107527 % 작업중...
0.44086021505376344 % 작업중...
0.4435483870967742 % 작업중...
0.44623655913978494 % 작업중...
0.4489247311827957 % 작업중...
0.45161290322580644 % 작업중...
0.4543010752688172 % 작업중...
0.45698924731182794 % 작업중...
0.4596774193548387 % 작업중...
0.46236559139784944 % 작업중...
0.4650537634408602 % 작업중...
0.46774193548387094 % 작업중...
0.47043010752688175 % 작업중...
0.4731182795698925 % 작업중...
0.47580645161290325 % 작업중...
0.478494623655914 % 작업중...
0.48118279569892475 % 작업중...
0.4838709677419355 % 작업중...
0.48655913978494625 % 작업중...
0.489247311827957 % 작업중...
0.49193548387096775 % 작업중...
0.4946236559139785 % 작업중...
0.49731182795698925 % 작업중...
0.5 % 작업중...
0.5026881720430108 % 작업중...
0.5053763440860215 % 작업중...
0.5080645161290323 % 작업중...
0.510752688172043 % 작업중...
0.5134408602150538 % 작업중...
0.5161290322580645 % 작업중...
0.5188172043010753 % 작업중...
0.521505376344086 % 작업중...
0.5241935483870968 % 작업중...
0.5268817204301075 % 작업중...
0.5295698924731183 % 작업중...
0.532258064516129 % 작업중...
0.5349462365591398 % 작업중...
0.5376344086021505 % 작업중...
0.5403225806451613 % 작업중...
0.543010752688172 % 작업중...
0.5456989247311828 % 작업중...
0.5483870967741935 % 작업중...
0.5510752688172043 % 작업중...
0.553763440860215 % 작업중...
0.5564516129032258 % 작업중...
0.5591397849462365 % 작업중...
0.5618279569892473 % 작업중...
0.5645161290322581 % 작업중...
0.5672043010752689 % 작업중...
0.5698924731182796 % 작업중...
0.5725806451612904 % 작업중...
0.5752688172043011 % 작업중...
0.5779569892473119 % 작업중...
0.5806451612903226 % 작업중...
0.5833333333333334 % 작업중...
0.5860215053763441 % 작업중...
0.5887096774193549 % 작업중...
0.5913978494623656 % 작업중...
0.5940860215053764 % 작업중...
0.5967741935483871 % 작업중...
0.5994623655913979 % 작업중...
0.6021505376344086 % 작업중...
0.6048387096774194 % 작업중...
0.6075268817204301 % 작업중...
0.6102150537634409 % 작업중...
0.6129032258064516 % 작업중...
0.6155913978494624 % 작업중...
0.6182795698924731 % 작업중...
0.6209677419354839 % 작업중...
0.6236559139784946 % 작업중...
0.6263440860215054 % 작업중...
0.6290322580645161 % 작업중...
0.6317204301075269 % 작업중...
0.6344086021505376 % 작업중...
0.6370967741935484 % 작업중...
0.6397849462365591 % 작업중...
0.6424731182795699 % 작업중...
0.6451612903225806 % 작업중...
0.6478494623655914 % 작업중...
0.6505376344086021 % 작업중...
0.6532258064516129 % 작업중...
0.6559139784946236 % 작업중...
0.6586021505376344 % 작업중...
0.6612903225806451 % 작업중...
0.6639784946236559 % 작업중...
0.6666666666666666 % 작업중...
0.6693548387096774 % 작업중...
0.6720430107526881 % 작업중...
0.6747311827956989 % 작업중...
0.6774193548387096 % 작업중...
0.6801075268817204 % 작업중...
0.6827956989247311 % 작업중...
0.6854838709677419 % 작업중...
0.6881720430107527 % 작업중...
0.6908602150537635 % 작업중...
0.6935483870967742 % 작업중...
0.696236559139785 % 작업중...
0.6989247311827957 % 작업중...
0.7016129032258065 % 작업중...
0.7043010752688172 % 작업중...
0.706989247311828 % 작업중...
0.7096774193548387 % 작업중...
0.7123655913978495 % 작업중...
0.7150537634408602 % 작업중...
0.717741935483871 % 작업중...
0.7204301075268817 % 작업중...
0.7231182795698925 % 작업중...
0.7258064516129032 % 작업중...
0.728494623655914 % 작업중...
0.7311827956989247 % 작업중...
0.7338709677419355 % 작업중...
0.7365591397849462 % 작업중...
0.739247311827957 % 작업중...
0.7419354838709677 % 작업중...
0.7446236559139785 % 작업중...
0.7473118279569892 % 작업중...
0.75 % 작업중...
0.7526881720430108 % 작업중...
0.7553763440860215 % 작업중...
0.7580645161290323 % 작업중...
0.760752688172043 % 작업중...
0.7634408602150538 % 작업중...
0.7661290322580645 % 작업중...
0.7688172043010753 % 작업중...
0.771505376344086 % 작업중...
0.7741935483870968 % 작업중...
0.7768817204301075 % 작업중...
0.7795698924731183 % 작업중...

0.782258064516129 % 작업중...
0.7849462365591398 % 작업중...
0.7876344086021505 % 작업중...
0.7903225806451613 % 작업중...
0.793010752688172 % 작업중...
0.7956989247311828 % 작업중...
0.7983870967741935 % 작업중...
0.8010752688172043 % 작업중...
0.803763440860215 % 작업중...
0.8064516129032258 % 작업중...
0.8091397849462365 % 작업중...
0.8118279569892473 % 작업중...
0.8145161290322581 % 작업중...
0.8172043010752689 % 작업중...
0.8198924731182796 % 작업중...
0.8225806451612904 % 작업중...
0.8252688172043011 % 작업중...
0.8279569892473119 % 작업중...
0.8306451612903226 % 작업중...
0.8333333333333334 % 작업중...
0.8360215053763441 % 작업중...
0.8387096774193549 % 작업중...
0.8413978494623656 % 작업중...
0.8440860215053764 % 작업중...
0.8467741935483871 % 작업중...
0.8494623655913979 % 작업중...
0.8521505376344086 % 작업중...
0.8548387096774194 % 작업중...
0.8575268817204301 % 작업중...
0.8602150537634409 % 작업중...
0.8629032258064516 % 작업중...
0.8655913978494624 % 작업중...
0.8682795698924731 % 작업중...
0.8709677419354839 % 작업중...
0.8736559139784946 % 작업중...
0.8763440860215054 % 작업중...
0.8790322580645161 % 작업중...
0.8817204301075269 % 작업중...
0.8844086021505376 % 작업중...
0.8870967741935484 % 작업중...
0.8897849462365591 % 작업중...
0.8924731182795699 % 작업중...
0.8951612903225806 % 작업중...
0.8978494623655914 % 작업중...
0.9005376344086021 % 작업중...
0.9032258064516129 % 작업중...
0.9059139784946236 % 작업중...
0.9086021505376344 % 작업중...
0.9112903225806451 % 작업중...
0.9139784946236559 % 작업중...
0.9166666666666666 % 작업중...
0.9193548387096774 % 작업중...
0.9220430107526881 % 작업중...
0.9247311827956989 % 작업중...
0.9274193548387096 % 작업중...
0.9301075268817204 % 작업중...
0.9327956989247311 % 작업중...
0.9354838709677419 % 작업중...
0.9381720430107527 % 작업중...
0.9408602150537635 % 작업중...
0.9435483870967742 % 작업중...
0.946236559139785 % 작업중...
0.9489247311827957 % 작업중...
0.9516129032258065 % 작업중...
0.9543010752688172 % 작업중...
0.956989247311828 % 작업중...
0.9596774193548387 % 작업중...
0.9623655913978495 % 작업중...
0.9650537634408602 % 작업중...
0.967741935483871 % 작업중...
0.9704301075268817 % 작업중...
0.9731182795698925 % 작업중...
0.9758064516129032 % 작업중...
0.978494623655914 % 작업중...
0.9811827956989247 % 작업중...
0.9838709677419355 % 작업중...
0.9865591397849462 % 작업중...
0.989247311827957 % 작업중...
0.9919354838709677 % 작업중...
0.9946236559139785 % 작업중...
0.9973118279569892 % 작업중...

,index,학정번호,학점,교과목명,담당교수,강의시간,강의실,index,정원,참여인원,...,4학년정원,교환학생가능여부,MaxMileage,최대값,최소값,평균값,중간값,분산,평균학년,재수강비율
0,0,ENG1108-01-01,3,공학정보처리,김은진,"월6,7(월8,9)",공D507(공A213),1,30,37,...,1,X,36,36,1,12.38,10.0,41.352853,2.054054,0.972973
0,1,ENG1108-01-02,3,공학정보처리,김은진,"월6,7(수4,5)",공D507(공A213),1,30,7,...,1,X,36,24,1,8.57,10.0,71.619048,2.285714,0.857143
0,2,ENG1108-02-01,3,공학정보처리,김은진,"목2,3(목4,5)",공D507(공A213),1,30,26,...,1,X,36,36,2,13.15,10.0,69.655385,2.115385,0.961538
0,3,ENG1108-02-02,3,공학정보처리,김은진,"목2,3(금5,6)",공D507(공A213),1,30,22,...,1,X,36,21,4,8.18,7.0,16.155844,2.090909,0.954545
0,4,ENG1108-03-01,3,공학정보처리,우호진,"목5,6(월7,8)",공D403(공B017),1,30,47,...,0,X,36,36,1,9.66,8.0,37.838113,2.234043,0.978723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,367,MAT4105-01-00,3,수학특강(1),박승경,"화4,5,목4(목5)",과B101(과B101),1,38,11,...,20,O,36,5,1,1.82,1.0,1.963636,3.727273,0.909091
0,368,MAT4112-01-00,3,체론,서수길,"수9,10,금9(금10)",과225(과225),1,40,18,...,20,O,36,15,1,3.89,1.5,16.692810,3.888889,0.944444
0,369,MAT4119-01-00,3,금융수학,김정훈,"화8,9,목6(목7)",과B103(과B103),1,40,26,...,20,O,36,35,1,5.46,1.0,70.098462,3.846154,0.961538
0,370,MAT4331-01-00,3,대수기하,최성락,"월5,6,수5(수6)",과B103(과B103),1,40,8,...,20,O,36,13,1,3.75,1.5,21.357143,4.000000,0.875000
0,371,MAT2016-15-00,3,공학수학(3),천세훈,"월1,2,수1(수2)",I진B320(I진B320),1,30,44,...,0,X,36,22,2,11,10.0,33.534884,2.136364,0.977273

In [11]:
data_df = pd.read_json('./2020_1.json',lines=True)

In [5]:
data_df

,_id,학정번호,학점,교과목명,담당교수,강의시간,강의실,마일리지정보,세부정보
0,{'$oid': '5ebac634a254fb2ba8e88171'},BIO3119-01-00,3.0,유전학,이명민,"화1,2,목2",과B133,"{'정원': '70', '참여인원': '58', '전공자정원': '60 (Y)', ...","[{'순위': '1', '마일리지': '21', '전공자': 'N (N)', '신청..."
1,{'$oid': '5ebac634a254fb2ba8e88172'},BIO2208-01-00,2.0,현대생명과학및연구입문,김지현,"금2,3",과S118B,"{'정원': '35', '참여인원': '11', '전공자정원': '30 (Y)', ...","[{'순위': '1', '마일리지': '7', '전공자': 'Y (Y)', '신청과..."
2,{'$oid': '5ebac634a254fb2ba8e88173'},BIO2207-01-00,3.0,생명체의진화와다양성,이명민,"화8,목7,8",과S118B,"{'정원': '35', '참여인원': '30', '전공자정원': '30 (Y)', ...","[{'순위': '1', '마일리지': '20', '전공자': 'Y (Y)', '신청..."
3,{'$oid': '5ebac634a254fb2ba8e88174'},BIO3120-01-00,3.0,환경생물학,성정희,"수2,3,4",과S321,"{'정원': '18', '참여인원': '15', '전공자정원': '15 (Y)', ...","[{'순위': '1', '마일리지': '28', '전공자': 'Y (Y)', '신청..."
4,{'$oid': '5ebac634a254fb2ba8e88175'},CHE2103-YY-00,3.0,유기화학(1),,,,"{'정원': '정보없음', '참여인원': '정보없음', '전공자정원': '정보없음'...",[]
...,...,...,...,...,...,...,...,...,...
3051,{'$oid': '5ebac636a254fb2ba8e88e54'},CDM3003-01-00,3.0,DESIGN 3: DESIGN AND PROTOTYPING,이현경,"목6,7,8,9/목6,7,8,9",I진B309/I지C101,"{'정원': '25', '참여인원': '4', '전공자정원': '25 (Y)', '...","[{'순위': '1', '마일리지': '11', '전공자': 'Y (Y)', '신청..."
3052,{'$oid': '5ebac636a254fb2ba8e88e55'},CDM3005-01-00,3.0,DESIGN PROJECT MANAGEMENT,서승교,"목3,4,5",I진B204,"{'정원': '25', '참여인원': '14', '전공자정원': '25 (Y)', ...","[{'순위': '1', '마일리지': '15', '전공자': 'Y (Y)', '신청..."
3053,{'$oid': '5ebac636a254fb2ba8e88e56'},CDM3008-01-00,3.0,ART AND CULTURE MARKETING,이슬기,"수4,5,6",대별208,"{'정원': '25', '참여인원': '39', '전공자정원': '25 (Y)', ...","[{'순위': '1', '마일리지': '36', '전공자': 'Y (Y)', '신청..."
3054,{'$oid': '5ebac636a254fb2ba8e88e58'},CDM4003-01-00,3.0,STRATEGIC MARKETING,한국인,"수7,8,9",대별208,"{'정원': '25', '참여인원': '44', '전공자정원': '25 (Y)', ...","[{'순위': '1', '마일리지': '36', '전공자': 'Y (Y)', '신청..."
3055,{'$oid': '5ebac636a254fb2ba8e88e59'},CDM4004-01-00,6.0,ACADEMIC-INDUSTRY PROJECT,오상은,"금2,3,4,5,6,7",대별B106,"{'정원': '50', '참여인원': '35', '전공자정원': '50 (Y)', ...","[{'순위': '1', '마일리지': '36', '전공자': 'Y (Y)', '신청..."

In [12]:
data_pp1 = data_df.drop(['_id','마일리지정보','세부정보'], axis=1)

In [13]:
data_pp1

,학정번호,학점,교과목명,담당교수,강의시간,강의실
0,BIO3119-01-00,3.0,유전학,이명민,"화1,2,목2",과B133
1,BIO2208-01-00,2.0,현대생명과학및연구입문,김지현,"금2,3",과S118B
2,BIO2207-01-00,3.0,생명체의진화와다양성,이명민,"화8,목7,8",과S118B
3,BIO3120-01-00,3.0,환경생물학,성정희,"수2,3,4",과S321
4,CHE2103-YY-00,3.0,유기화학(1),,,
...,...,...,...,...,...,...
3051,CDM3003-01-00,3.0,DESIGN 3: DESIGN AND PROTOTYPING,이현경,"목6,7,8,9/목6,7,8,9",I진B309/I지C101
3052,CDM3005-01-00,3.0,DESIGN PROJECT MANAGEMENT,서승교,"목3,4,5",I진B204
3053,CDM3008-01-00,3.0,ART AND CULTURE MARKETING,이슬기,"수4,5,6",대별208
3054,CDM4003-01-00,3.0,STRATEGIC MARKETING,한국인,"수7,8,9",대별208
3055,CDM4004-01-00,6.0,ACADEMIC-INDUSTRY PROJECT,오상은,"금2,3,4,5,6,7",대별B106

In [14]:
data_df.columns

Index(['_id', '학정번호', '학점', '교과목명', '담당교수', '강의시간', '강의실', '마일리지정보', '세부정보'], dtype='object')

In [15]:
yonsei = pd.DataFrame()

for i in range(0, len(data_pp1.index)):
    df1 = pd.DataFrame(data_pp1.iloc[i,:],).transpose()
    df2 = pd.DataFrame(data_df['마일리지정보'][i].items()).set_index(0).transpose()
    df1 = df1.reset_index()
    df2 = df2.reset_index()
    df3 = pd.concat([df1, df2], axis=1)
    yonsei = yonsei.append(df3)

In [16]:
df1

,index,학정번호,학점,교과목명,담당교수,강의시간,강의실
0,3055,CDM4004-01-00,6,ACADEMIC-INDUSTRY PROJECT,오상은,"금2,3,4,5,6,7",대별B106

In [17]:
pd.DataFrame(data_df['세부정보'][2][9].items()).set_index(0).transpose()

0  순위 마일리지    전공자 신청과목수 졸업신청 초수강여부    총/졸업   직전/학기 학년 수강여부 비고
1  10    3  Y (Y)     6    N     Y  0.8370  0.7631  4    O

In [18]:
yonsei['분산'] = 0

In [19]:
df1 = pd.DataFrame()
for j in range(0, len(data_df['세부정보'][0])):
    df2 = pd.DataFrame(data_df['세부정보'][0][j].items()).set_index(0).transpose()
    df1 = df1.append(df2)
    df1.set_index('순위', inplace=True)
    df1['마일리지'] = pd.to_numeric(df1['마일리지'])
    df1['학년'] = pd.to_numeric(df1['학년'])
    yonsei.iloc[i,-1] = df1.loc[:,'마일리지'].var()

In [49]:
from tensorflow.keras.utils import to_categorical

In [20]:
for k in range(0,len(df1)):
    if df1.iloc[k,4] == 'Y':
        df1.iloc[k,4] = 0
    else:
        df1.iloc[k,4] = 1

In [56]:
df1.iloc[3,4] = 1

In [21]:
df1['초수강여부'].mean()

0.034482758620689655

df3 = df1.set_index('순위')

df3

df3['마일리지'] = pd.to_numeric(df3['마일리지'])
df3['학년'] = pd.to_numeric(df3['학년'])

df3.info()

df3.loc[:,'학년'].mean()

pd.DataFrame(data_df['세부정보'][0][1].items()).set_index(0).transpose()

len(data_df['세부정보'])

data_df['마일리지정보'][1]

In [21]:
yonsei

,index,학정번호,학점,교과목명,담당교수,강의시간,강의실,index,정원,참여인원,전공자정원,1학년정원,2학년정원,3학년정원,4학년정원,교환학생가능여부,MaxMileage,최대값,최소값,평균값
0,0,BIO3119-01-00,3,유전학,이명민,"화1,2,목2",과B133,1,70,58,60 (Y),0,0,0,0,O,36,21,1,4.86
0,1,BIO2208-01-00,2,현대생명과학및연구입문,김지현,"금2,3",과S118B,1,35,11,30 (Y),0,0,0,0,O,36,7,1,2.91
0,2,BIO2207-01-00,3,생명체의진화와다양성,이명민,"화8,목7,8",과S118B,1,35,30,30 (Y),0,0,0,0,O,36,20,1,3.27
0,3,BIO3120-01-00,3,환경생물학,성정희,"수2,3,4",과S321,1,18,15,15 (Y),0,0,0,0,O,36,28,1,8.07
0,4,CHE2103-YY-00,3,유기화학(1),,,,1,정보없음,정보없음,정보없음,정보없음,정보없음,정보없음,정보없음,정보없음,정보없음,정보없음,정보없음,정보없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,3051,CDM3003-01-00,3,DESIGN 3: DESIGN AND PROTOTYPING,이현경,"목6,7,8,9/목6,7,8,9",I진B309/I지C101,1,25,4,25 (Y),0,0,0,0,X,36,11,1,5.75
0,3052,CDM3005-01-00,3,DESIGN PROJECT MANAGEMENT,서승교,"목3,4,5",I진B204,1,25,14,25 (Y),0,0,0,0,X,36,15,1,5.29
0,3053,CDM3008-01-00,3,ART AND CULTURE MARKETING,이슬기,"수4,5,6",대별208,1,25,39,25 (Y),0,0,0,0,X,36,36,7,19.15
0,3054,CDM4003-01-00,3,STRATEGIC MARKETING,한국인,"수7,8,9",대별208,1,25,44,25 (Y),0,0,0,0,X,36,36,1,11.39
0,3055,CDM4004-01-00,6,ACADEMIC-INDUSTRY PROJECT,오상은,"금2,3,4,5,6,7",대별B106,1,50,35,50 (Y),0,0,0,0,X,36,36,1,7.43

In [ ]:
# data_pp1.to_excel('generals.xlsx')