In [1]:
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import rc, font_manager
from datetime import datetime
from datetime import timedelta
import numpy as np

In [2]:
카테고리 = pd.read_excel('04_혁신아이디어분야_유통데이터(GS리테일)_데이터정의서 및 문제 데이터.xlsx', 
              sheet_name = '카테고리(행열변환)')

In [3]:
카테고리

,ADMD,소공동,소공동.1,소공동.2,소공동.3,소공동.4,소공동.5,소공동.6,소공동.7,회현동,...,고산2동.6,고산2동.7,고산3동,고산3동.1,고산3동.2,고산3동.3,고산3동.4,고산3동.5,고산3동.6,고산3동.7
0,ANTC_ITEM_LCLS_NM,식사,간식,마실거리,홈&리빙,헬스&뷰티,취미&여가활동,사회활동,임신/육아,식사,...,사회활동,임신/육아,식사,간식,마실거리,홈&리빙,헬스&뷰티,취미&여가활동,사회활동,임신/육아
1,20190201,0.287643,0.185728,0.383557,0.0417394,0.0814831,0.00421516,0.0107495,0.00488442,0.31416,...,0.00889254,0.000912982,0.359978,0.196602,0.376762,0.0134078,0.029606,0.00911737,0.00883059,0.00569657
2,20190202,0.304,0.227291,0.344574,0.0280217,0.0842294,0.00267992,0.00667843,0.00252645,0.318835,...,0.0160977,0.0112837,0.383677,0.202343,0.314493,0.0076572,0.0557725,0.00984422,0.0201634,0.00604917
3,20190203,0.275632,0.225132,0.271592,0.0173874,0.187566,0.00255173,0.0164333,0.00370641,0.365787,...,0.0156605,0.000510598,0.336969,0.226798,0.334047,0.0118217,0.0774399,NaN,0.00924039,0.00368276
4,20190204,0.355523,0.238465,0.3084,0.0150141,0.0572854,0.00563946,0.0175001,0.00217293,0.358589,...,0.0105611,0.0126123,0.31706,0.231654,0.340809,0.0157136,0.0664125,0.00662528,0.0166608,0.0050647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,20200527,0.265204,0.200248,0.42904,0.0257,0.0680921,0.00251485,0.00824327,0.000957538,0.276798,...,0.00893776,0.00843776,0.299797,0.194124,0.420436,0.00644061,0.0471621,0.0155503,0.0034554,0.0130349
238,20200528,0.2511,0.195551,0.421532,0.0432449,0.0754776,0.00357381,0.00932501,0.000195903,0.280247,...,0.00311864,0.0095439,0.290565,0.197811,0.434137,0.0121549,0.0480956,0.00504503,0.00763711,0.00455559
239,20200529,0.239728,0.225265,0.430289,0.0266036,0.0617742,0.00812337,0.00715852,0.00105891,0.268368,...,0.0133786,0.00251187,0.356241,0.202658,0.374992,0.0113505,0.0418418,0.00637631,NaN,0.00653985
240,20200530,0.230298,0.213128,0.430194,0.0424352,0.0698201,0.00450064,0.00660175,0.00302247,0.270163,...,0.00775103,0.0136183,0.293103,0.255332,0.384444,0.0120947,0.0450934,0.0036741,0.00224172,0.00401729
241,20200531,0.324881,0.191642,0.37488,0.0197902,0.0703207,0.00629418,0.0116423,0.000548687,0.31675,...,0.0200806,0.00968374,0.279122,0.218369,0.39595,0.0349346,0.0511652,0.00571029,0.00752712,0.00722114

In [4]:
header = 카테고리.iloc[0]
카테고리.rename(columns=header)

,ANTC_ITEM_LCLS_NM,식사,간식,마실거리,홈&리빙,헬스&뷰티,취미&여가활동,사회활동,임신/육아,식사,...,사회활동,임신/육아,식사,간식,마실거리,홈&리빙,헬스&뷰티,취미&여가활동,사회활동,임신/육아
0,ANTC_ITEM_LCLS_NM,식사,간식,마실거리,홈&리빙,헬스&뷰티,취미&여가활동,사회활동,임신/육아,식사,...,사회활동,임신/육아,식사,간식,마실거리,홈&리빙,헬스&뷰티,취미&여가활동,사회활동,임신/육아
1,20190201,0.287643,0.185728,0.383557,0.0417394,0.0814831,0.00421516,0.0107495,0.00488442,0.31416,...,0.00889254,0.000912982,0.359978,0.196602,0.376762,0.0134078,0.029606,0.00911737,0.00883059,0.00569657
2,20190202,0.304,0.227291,0.344574,0.0280217,0.0842294,0.00267992,0.00667843,0.00252645,0.318835,...,0.0160977,0.0112837,0.383677,0.202343,0.314493,0.0076572,0.0557725,0.00984422,0.0201634,0.00604917
3,20190203,0.275632,0.225132,0.271592,0.0173874,0.187566,0.00255173,0.0164333,0.00370641,0.365787,...,0.0156605,0.000510598,0.336969,0.226798,0.334047,0.0118217,0.0774399,NaN,0.00924039,0.00368276
4,20190204,0.355523,0.238465,0.3084,0.0150141,0.0572854,0.00563946,0.0175001,0.00217293,0.358589,...,0.0105611,0.0126123,0.31706,0.231654,0.340809,0.0157136,0.0664125,0.00662528,0.0166608,0.0050647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,20200527,0.265204,0.200248,0.42904,0.0257,0.0680921,0.00251485,0.00824327,0.000957538,0.276798,...,0.00893776,0.00843776,0.299797,0.194124,0.420436,0.00644061,0.0471621,0.0155503,0.0034554,0.0130349
238,20200528,0.2511,0.195551,0.421532,0.0432449,0.0754776,0.00357381,0.00932501,0.000195903,0.280247,...,0.00311864,0.0095439,0.290565,0.197811,0.434137,0.0121549,0.0480956,0.00504503,0.00763711,0.00455559
239,20200529,0.239728,0.225265,0.430289,0.0266036,0.0617742,0.00812337,0.00715852,0.00105891,0.268368,...,0.0133786,0.00251187,0.356241,0.202658,0.374992,0.0113505,0.0418418,0.00637631,NaN,0.00653985
240,20200530,0.230298,0.213128,0.430194,0.0424352,0.0698201,0.00450064,0.00660175,0.00302247,0.270163,...,0.00775103,0.0136183,0.293103,0.255332,0.384444,0.0120947,0.0450934,0.0036741,0.00224172,0.00401729
241,20200531,0.324881,0.191642,0.37488,0.0197902,0.0703207,0.00629418,0.0116423,0.000548687,0.31675,...,0.0200806,0.00968374,0.279122,0.218369,0.39595,0.0349346,0.0511652,0.00571029,0.00752712,0.00722114

In [5]:
df = 카테고리[1:].copy()
header = 카테고리.iloc[0]

In [6]:
df

,ADMD,소공동,소공동.1,소공동.2,소공동.3,소공동.4,소공동.5,소공동.6,소공동.7,회현동,...,고산2동.6,고산2동.7,고산3동,고산3동.1,고산3동.2,고산3동.3,고산3동.4,고산3동.5,고산3동.6,고산3동.7
1,20190201,0.287643,0.185728,0.383557,0.0417394,0.0814831,0.00421516,0.0107495,0.00488442,0.31416,...,0.00889254,0.000912982,0.359978,0.196602,0.376762,0.0134078,0.029606,0.00911737,0.00883059,0.00569657
2,20190202,0.304,0.227291,0.344574,0.0280217,0.0842294,0.00267992,0.00667843,0.00252645,0.318835,...,0.0160977,0.0112837,0.383677,0.202343,0.314493,0.0076572,0.0557725,0.00984422,0.0201634,0.00604917
3,20190203,0.275632,0.225132,0.271592,0.0173874,0.187566,0.00255173,0.0164333,0.00370641,0.365787,...,0.0156605,0.000510598,0.336969,0.226798,0.334047,0.0118217,0.0774399,NaN,0.00924039,0.00368276
4,20190204,0.355523,0.238465,0.3084,0.0150141,0.0572854,0.00563946,0.0175001,0.00217293,0.358589,...,0.0105611,0.0126123,0.31706,0.231654,0.340809,0.0157136,0.0664125,0.00662528,0.0166608,0.0050647
5,20190205,0.317881,0.269207,0.318957,0.0156428,0.0618824,0.00330563,0.0120111,0.00111417,0.313585,...,0.0236221,0.0472247,0.279863,0.234279,0.363196,0.0157562,0.06526,0.0155207,0.0196409,0.0064852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,20200527,0.265204,0.200248,0.42904,0.0257,0.0680921,0.00251485,0.00824327,0.000957538,0.276798,...,0.00893776,0.00843776,0.299797,0.194124,0.420436,0.00644061,0.0471621,0.0155503,0.0034554,0.0130349
238,20200528,0.2511,0.195551,0.421532,0.0432449,0.0754776,0.00357381,0.00932501,0.000195903,0.280247,...,0.00311864,0.0095439,0.290565,0.197811,0.434137,0.0121549,0.0480956,0.00504503,0.00763711,0.00455559
239,20200529,0.239728,0.225265,0.430289,0.0266036,0.0617742,0.00812337,0.00715852,0.00105891,0.268368,...,0.0133786,0.00251187,0.356241,0.202658,0.374992,0.0113505,0.0418418,0.00637631,NaN,0.00653985
240,20200530,0.230298,0.213128,0.430194,0.0424352,0.0698201,0.00450064,0.00660175,0.00302247,0.270163,...,0.00775103,0.0136183,0.293103,0.255332,0.384444,0.0120947,0.0450934,0.0036741,0.00224172,0.00401729
241,20200531,0.324881,0.191642,0.37488,0.0197902,0.0703207,0.00629418,0.0116423,0.000548687,0.31675,...,0.0200806,0.00968374,0.279122,0.218369,0.39595,0.0349346,0.0511652,0.00571029,0.00752712,0.00722114

In [7]:
df['ADMD']=df['ADMD'].apply(lambda x: pd.to_datetime(str(x), format='%Y%m%d')).copy()

In [8]:
df20 = df[df.ADMD >= '2020-01-01'].copy()

In [9]:
df20.set_index('ADMD', inplace=True)
df20.fillna(0, inplace=True)

In [10]:
corona = pd.read_excel("확진자 현황.xlsx", sheet_name='종합')

In [11]:
corona.fillna(0, inplace=True)
corona.set_index('date', inplace = True)

In [12]:
자료 = pd.concat([corona, df20], axis=1, sort=True)

In [13]:
상관관계 = 자료.corr().iloc[4:,:4].copy()

In [14]:
상관관계
# 없으면 식사
# 1번은 간식
# 2번은 마실거리
# 3번은 홈/리빙
# 4번은 헬스/뷰티
# 5번은 취미/여가활동
# 6번은 사회활동
# 7번은 임신/육아

        new_cases  new_deaths  new_tests       검색량
소공동      0.412551    0.400556   0.201824  0.024896
소공동.1    0.009492   -0.120608  -0.216848  0.001893
소공동.2   -0.162018    0.115470   0.338409 -0.328067
소공동.3    0.089094    0.053984   0.080971  0.042674
소공동.4   -0.188244   -0.319484  -0.241104  0.301887
...           ...         ...        ...       ...
고산3동.3  -0.097968   -0.124629  -0.086309 -0.085246
고산3동.4   0.249830   -0.127721  -0.045833  0.651977
고산3동.5  -0.054802   -0.032187  -0.028868  0.007281
고산3동.6  -0.195661   -0.021371  -0.174676 -0.008033
고산3동.7  -0.116390   -0.147312  -0.076065 -0.108513

[480 rows x 4 columns]

In [15]:
상관관계['종합점수'] = abs(상관관계.new_cases) + abs(상관관계.new_deaths) + abs(상관관계.new_tests) + abs(상관관계.검색량)

In [16]:
상관관계.sort_values(by = '종합점수', ascending=False).head(50)

          new_cases  new_deaths  new_tests       검색량      종합점수
범어1동       0.512554    0.401923   0.300737  0.211662  1.426876
성내1동       0.536042    0.484968   0.301900  0.069021  1.391931
성내2동       0.462294    0.534914   0.272324  0.112437  1.381969
을지로동.4    -0.172823   -0.371500  -0.327015  0.451939  1.323277
상계10동.4   -0.231910   -0.341598  -0.216606  0.508017  1.298132
을지로동       0.468260    0.375165   0.282721 -0.149255  1.275402
하계2동.4    -0.021200   -0.367892  -0.225499  0.640257  1.254848
광희동.4     -0.159329   -0.370159  -0.293090  0.427615  1.250193
상계1동.4    -0.095319   -0.362383  -0.223308  0.565843  1.246852
을지로동.2    -0.081859    0.294763   0.369575 -0.493531  1.239728
성내2동.2    -0.504723   -0.206879  -0.034547 -0.456712  1.202861
중계2.3동     0.439913    0.344131   0.343485  0.074680  1.202209
장충동.4     -0.069232   -0.305102  -0.240452  0.583182  1.197967
필동         0.365752    0.400961   0.268209 -0.158660  1.193583
수성1가동.4    0.364526   -0.127991   0.106969  0.586245  1.185731
공릉2동.4    -0.095322   -0.312284  -0.195421  0.580754  1.183781
다산동.4     -0.155520   -0.359869  -0.237990  0.425082  1.178461
필동.4      -0.107643   -0.317142  -0.241500  0.505512  1.171797
중계본동.4     0.094101   -0.313252  -0.134560  0.624606  1.166519
황학동.4     -0.191299   -0.335443  -0.266487  0.373174  1.166403
남산4동.4     0.443966   -0.011517   0.235232  0.469900  1.160615
남산4동.1    -0.337806   -0.248862  -0.242430 -0.322729  1.151827
만촌3동.4     0.173590   -0.186634  -0.086426  0.703427  1.150077
월계1동.4    -0.097203   -0.351794  -0.183672  0.510271  1.142939
월계2동.4     0.091633   -0.224787  -0.172597  0.632920  1.121937
두산동        0.409217    0.153334   0.156262  0.399861  1.118675
남산1동.4     0.129071   -0.205543  -0.041325  0.732600  1.108539
상계2동.4    -0.116803   -0.375516  -0.170752  0.438957  1.102028
중계2.3동.4  -0.101649   -0.385898  -0.134797  0.474088  1.096432
황금1동.4     0.273623   -0.146157   0.129934  0.543916  1.093630
범어3동.4     0.170119   -0.275774  -0.041529  0.601636  1.089058
황금2동.2    -0.432391   -0.083014   0.119342 -0.450755  1.085502
황금2동.4     0.227101   -0.200230   0.012479  0.636669  1.076480
신당5동.4    -0.207097   -0.292978  -0.276440  0.299460  1.075976
고산3동.4     0.249830   -0.127721  -0.045833  0.651977  1.075361
지산1동.4     0.228689   -0.167670  -0.061035  0.614080  1.071474
남산1동.2    -0.353623   -0.061691   0.080263 -0.572684  1.068261
약수동.4     -0.055350   -0.242824  -0.249261  0.517454  1.064889
명동         0.453719    0.405458   0.157627  0.045548  1.062352
성내3동.2    -0.397000   -0.140079   0.029813 -0.490134  1.057025
하계1동.4    -0.149245   -0.334067  -0.156228  0.415633  1.055173
소공동.4     -0.188244   -0.319484  -0.241104  0.301887  1.050719
고산1동.4     0.201370   -0.206575  -0.068093  0.573693  1.049730
명동.4      -0.129503   -0.333478  -0.223273  0.359891  1.046145
광희동        0.382487    0.377049   0.203246  0.078621  1.041402
소공동        0.412551    0.400556   0.201824  0.024896  1.039826
상계3.4동.4  -0.029966   -0.256230  -0.182177  0.570871  1.039244
범어1동.4     0.027890   -0.264530  -0.165152  0.580901  1.038472
범어2동.2    -0.305811   -0.068016   0.232692 -0.428328  1.034846
청구동.4     -0.078306   -0.255064  -0.184260  0.505500  1.023130

In [17]:
확진자_상관관계 = 상관관계.drop(axis=1, columns=상관관계.columns[[1,2,3,4]])

In [18]:
temp = 확진자_상관관계[(확진자_상관관계.new_cases >= 0.2) | (확진자_상관관계.new_cases <= -0.2)]

In [19]:
temp.sort_values(by = 'new_cases')

          new_cases
성내2동.2    -0.504723
황금2동.2    -0.432391
성내3동.2    -0.397000
중계2.3동.7  -0.378758
고산3동.2    -0.355050
...             ...
명동         0.453719
성내2동       0.462294
을지로동       0.468260
범어1동       0.512554
성내1동       0.536042

[105 rows x 1 columns]

In [20]:
import os
base_dir = 'E:\문서\DataCam\팀플'
file_nm = "편의점_카테고리.xlsx"
xlxs_dir = os.path.join(base_dir, file_nm)

In [21]:
temp.to_excel(xlxs_dir, # directory and file name to write
            sheet_name = '서울', 
            na_rep = 'NaN', 
            float_format = "%.2f", 
            header = True, 
            index = True, 
            index_label = "id", 
            startrow = 1, 
            startcol = 1, 
            )